# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a5bacfa2ff27b45a6e034a476f8791de7bb1b3ffbf0d446f0b0980865c43bff41b9793cc2f2ac296c6ab0408b5a2e66099060a6b6d85f40f6fa8266443d8b26

test:
  secret_key_base: e4b6d86ea776fc44000a19e13505d652dcab7519f4001b283c2dc22f8d7e909ee88410378e3dd2d7bbe220160fc02932764f5601cec05391b5d10ac0f65acc72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
